Notepad++ v8.6.2 fixed regressions:

 1. Fix Shift-DEL, Ctrl-INS and Shift-INS not working regression.
 2. Fix Ctrl+V cannot paste into the text fields of certain plugins regression.
 3. Remove option "disableLineCopyCutDelete.xml" (the empty file takes no effect).
 4. Fix a regression: the position in the previous session is now restored correctly in cloned document.


Notepad++ v8.6.1 new features & bug-fixes:

 1. Updated to Scintilla 5.4.1 & Lexilla 5.3.0.
 2. Fix a regression: customized extension in Style Configurator is now saved correctly.
 3. Add an ability (disableLineCopyCutDelete.xml) to disable line copy/cut/delete when no selection is made.
 4. Add an ability (noColumnToMultiSelect.xml) to disable column mode to multi-select mode.
 5. Fix deleting in column mode also delete an unexpected EOL.
 6. Fix hidden results of long lines for Search results with "Find in..." commands.
 7. Enhance Search-results by showing search options for "Find in..." commands.
 8. Fix an issue: replacements are no longer duplicated (the 2nd time in cloned document) for "Replace in Opened Docs".
 9. Fix a regression to make F3 & Shift-F3 work again in Incremental Search.
10. Add document tab navigation commands: "First tab" & "Last tab".
11. Add document tab commands: "Move to Start" & "Move to End" commands.
12. 3 RTL new abilities: RTL per document, RTL per document remembered across the sessions & new attribute editZoneRTL="no" in RTL localization files.
13. Enhance the "-loadingTime" command line parameter.
14. Enhance the performance: disable undo collection while loading a file.
15. Sort language list in the Preferences dialog.
16. Fix a visual glitch that occurred during multi-paste.
17. Fix confusing memory allocation error message.
18. Fix python wrong decorator attribute color.
19. Fix file status in "other view" is not detected.
20. Fix dropped file being opened in the wrong view.


Get more info on
https://notepad-plus-plus.org/downloads/v8.6.2/


Included plugins:

1.  NppExport v0.4
2.  Converter v4.5
3.  Mime Tool v3.0


Updater (Installer only):

* WinGUp (for Notepad++) v5.2.7
CREATE TABLE HISTORIAM ( 

id_oper NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

data_operacji DATE NOT NULL, 

tabela VARCHAR2(20) NOT NULL, 

operacja VARCHAR2(20) NOT NULL 

); 

  

select * FROM PRACOWNIcy_am; 

drop table pracownicy_am; 

create table pracownicy_am as select employee_id, last_name, first_name, hire_date, salary, job_id, department_id from hr.employees; 

  

CREATE OR REPLACE TRIGGER zapisz_insert 

AFTER Insert ON pracownicy_am 

BEGIN 

INSERT INTO HISTORIAM(data_operacji, tabela, operacja) VALUES(sysdate,'Pracownicy','Insert'); 

END; 

/ 

  

CREATE OR REPLACE TRIGGER Historia_modyfikacji 

AFTER UPDATE OF SALARY,JOB_ID,DEPARTMENT_ID ON pracownicy_am 

FOR EACH ROW 

WHEN   (OLD.SALARY != NEW.SALARY OR 

        OLD.DEPARTMENT_ID !=NEW.DEPARTMENT_ID OR 

        OLD.JOB_ID != NEW.JOB_ID) 

BEGIN 

INSERT INTO HISTORIAM(id_prac,placa_pod,id_etat,id_wydzial,data_mod) VALUES(:OLD.EMPLOYEE_ID,:OLD.SALARY,:OLD.JOB_ID,:OLD.DEPARTMENT_ID,SYSDATE); 

END; 

  

/ 

--5 

CREATE TABLE errors_am ( 

    id_oper NUMBER GENERATED BY DEFAULT AS IDENTITY, 

    operacja VARCHAR2(10), 

    nazwa_pola VARCHAR2(20), 

    opis_bledu VARCHAR2(2000), 

    data_mod DATE DEFAULT SYSDATE 

); 

/ 

CREATE OR REPLACE TRIGGER SprawdzPoprawnosc_AM 

BEFORE INSERT OR UPDATE ON pracownicy_am 

FOR EACH ROW 

DECLARE 

    PRAGMA AUTONOMOUS_TRANSACTION; 

    l_error VARCHAR2(4000); 

    l_operacja VARCHAR2(10); 

BEGIN 

  

    IF INSERTING THEN 

        l_operacja := 'INSERT'; 

    ELSIF UPDATING THEN 

        l_operacja := 'UPDATE'; 

    END IF; 

  

    IF :NEW.salary < 0 THEN 

        l_error := 'Salary cannot be less than 0'; 

        INSERT INTO errors_am (operacja, nazwa_pola, opis_bledu)  

        VALUES (l_operacja, 'salary', l_error); 

        COMMIT;  

        RAISE_APPLICATION_ERROR(-20001, l_error); 

    END IF; 

  

    IF :NEW.department_id < 0 THEN 

        l_error := 'Department ID cannot be less than 0'; 

        INSERT INTO errors_am (operacja, nazwa_pola, opis_bledu)  

        VALUES (l_operacja, 'department_id', l_error); 

        COMMIT; 

        RAISE_APPLICATION_ERROR(-20002, l_error); 

    END IF; 

END; 

/ 

  

  

INSERT INTO pracownicy_am (employee_id, first_name, last_name, hire_date, salary, job_id, department_id) 

    VALUES (301, 'Joh', 'Wick', TO_DATE('2020-01-01', 'YYYY-MM-DD'), -7000, 'IT_PROG', -10); 

  

select * from errors_am; 

  

--6 

CREATE OR REPLACE VIEW DEP_PRAC_ILE AS 

SELECT  

    d.department_name, 

    COUNT(p.employee_id) AS pracownik_count 

FROM  

    departments d 

LEFT JOIN  

    pracownicy_am p ON d.department_id = p.department_id 

GROUP BY  

    d.department_name; 

/ 

  

 

 