Create table JournalAM(
id_j number(7) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
date_j DATE NOT NULL,
table_j varchar(30) NOT NULL,
operation_j varchar(30) NOT NULL
);
/
select * from pracownicy_am;
/
create TRIGGER employeeFired
AFTER DELETE on pracownicy_am
Begin 
insert into JournalAM(date_j,table_j,operation_j)
vALUES (sysdate,'PRACONICY_AM','DELETE');
END;
/
create or replace TRIGGER journal_operation_AM
AFTER INSERT OR UPDATE OR DELETE ON pracownicy_am
FOR EACH ROW
BEGIN
    case
        WHEN INSERTING THEN
            INSERT INTO JournalAM(date_j,table_j,operation_j)
            values (sysdate, 'PRACOWNICY_AM', 'INSERT');
        WHEN UPDATING THEN
            INSERT INTO JournalAM(date_j,table_j,operation_j)
            values (sysdate, 'PRACOWNICY_AM', 'UPDATE');
        WHEN DELETING THEN
            INSERT INTO JournalAM(date_j,table_j,operation_j)
            values (sysdate, 'PRACOWNICY_AM', 'DELETE');
    END CASE;
END;    
/
CREATE or REPLACE PACKAGE narzedzia_AM AS
Function nazwa(text in varchar2) return NUMBER;
END narzedzia_AM;
/
CREATE OR REPLACE PACKAGE BODY narzedzia_AM AS
    Function nazwa(text in varchar2) RETURN number is
    i_v NUMBER :=0;
    Begin
    for i in 1..LENGTH(text) LOOP
        i_v:=1;
    END LOOP;
   RETURN i_v;
END nazwa;   
    
END narzedzia_AM;
/
    
/
CREATE OR REPLACE 
PACKAGE TEKSTOWE2 AS 
 FUNCTION ZLICZ_ZNK(napis IN VARCHAR2, znak IN CHAR) return NUMBER;
 FUNCTION OD_KONCA( napis in VARCHAR2) return varchar2;
 FUNCTION SRODEK (napis in varchar2) return varchar2;
 PROCEDURE POWT(napis in Varchar2);
END TEKSTOWE2;
/
Create or Replace PACKAGE BODY Tekstowe2 AS
    FUNCTION ZLICZ_ZNK(napis in varchar2, znak in char) return number is
    ile NUMBER:= 0;
    BEGIN
       FOR i IN 1..LENGTH(napis) LOOP
            IF SUBSTR(napis, i, 1) = znak THEN
                ile := ile + 1;
            END IF;
        END LOOP;
        RETURN ile;
    END ZLICZ_ZNK ;   
    FUNCTION OD_KONCA(napis IN VARCHAR2) RETURN VARCHAR2 IS
        odwr_napis VARCHAR2(32767);
    BEGIN
        FOR i IN REVERSE 1..LENGTH(napis) LOOP
            odwr_napis := odwr_napis || SUBSTR(napis, i, 1);
        END LOOP;
        RETURN odwr_napis;
    END OdKonca;


END TEKSTOWE2
/
Create or Replace Package PlacaAM IS
procedure ZmienPensja(id_p in number, kwota in number, p_decyzja in char);
end PlacaAM;
/
Create or Replace Package Body PlacaAM is
procedure ZmienPensja(id_p in number, kwota in number, p_decyzja in char) is
begin
if p_decyzja='p'
then update pracownicy_am set salary=salary+kwota where employee_id = id_p;
else update pracownicy_am set salary=salary-kwota where employee_id = id_p;
end if;
end ZmienPensja;
end PlacaAM;
/
create table dummy_tableAM as select * from hr.employees;
drop table departament_AM;
create table departamenty_AM as select * from hr.departments;
select * from departamenty_AM;
/
Create or Replace VIEW widok_J AS
select d.department_name, count(p.employee_id) as liczba 
from pracownicy_AM p join departamenty_AM d on p.department_id = d.department_id
GROUP BY d.department_name;
/
Create Trigger insert_dep
INSTEAD of insert on dummy_tableAM
Begin
insert into departamenty_AM(department_id, department_name)
VALUES((select max(department_id)+10 from departamenty), :NEW.department_name);
END;
/
--grant execute on 